competition_game:
    resource: "@CompetitionGameBundle/Resources/config/routing.yml"
    prefix:   /

competition_match:
    resource: "@CompetitionMatchBundle/Resources/config/routing.yml"
    prefix:   /

competition_blog:
    resource: "@CompetitionBlogBundle/Resources/config/routing.yml"
    prefix:   /

competition_team:
    resource: "@CompetitionTeamBundle/Resources/config/routing.yml"
    prefix:   /


competition_frontend:
    resource: "@CompetitionFrontendBundle/Resources/config/routing.yml"
    prefix:   /

_user_bundle:
    resource: "@CompetitionUserBundle/Resources/config/routing.yml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal


