Competition\UserBundle\Entity\User:
    properties:
        username:
            - NotBlank:
            - MinLength:
                limit: 3
            - MaxLength:
                limit: 64
        email:
            - Email:
                checkMX: true
        name:
            - MinLength:
                limit: 3
            - MaxLength:
                limit: 255
        surname:
            - MinLength:
                limit: 3
            - MaxLength:
                limit: 255